# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAN', models.CharField(help_text='Mandatory', max_length=10, verbose_name='PAN')),
                ('TAN', models.CharField(blank=True, max_length=10, null=True, verbose_name='TAN')),
                ('STN', models.CharField(blank=True, max_length=15, null=True, verbose_name='Service Tax Regn. No.')),
                ('CExNo', models.CharField(blank=True, max_length=15, null=True, verbose_name='Central Excise Regn. No.')),
                ('DOB', models.DateField(help_text='Mandatory', verbose_name='Date of Birth / Registration')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(max_length=1000, verbose_name='User Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clients.Client')),
                ('First_Name', models.CharField(help_text='Mandatory', max_length=20, verbose_name='First Name')),
                ('Middle_Name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Middle Name')),
                ('Last_Name', models.CharField(help_text='Mandatory', max_length=20, verbose_name='Last Name')),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], help_text='Mandatory', max_length=1, verbose_name='Gender')),
            ],
            bases=('clients.client',),
        ),
        migrations.CreateModel(
            name='Limited_Company',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clients.Client')),
                ('Company_Name', models.CharField(help_text='Mandatory', max_length=120, verbose_name='Company Name')),
                ('Company_CIN', models.CharField(help_text='Mandatory', max_length=21, verbose_name='Company CIN')),
                ('Company_Type', models.CharField(choices=[('pvt', 'Pvt_Ltd'), ('pub', 'Pub_Ltd'), ('opc', 'OPC')], default='pvt', help_text='Mandatory', max_length=3, verbose_name='Company Type')),
            ],
            bases=('clients.client',),
        ),
        migrations.CreateModel(
            name='LLP',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clients.Client')),
                ('LLP_Name', models.CharField(help_text='Mandatory', max_length=80, verbose_name='LLP Name')),
                ('LLPIN', models.CharField(help_text='Mandatory', max_length=8, verbose_name='LLP Identification Number')),
            ],
            bases=('clients.client',),
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clients.Client')),
                ('Partnership_Name', models.CharField(help_text='Mandatory', max_length=80, verbose_name='LLP Name')),
            ],
            bases=('clients.client',),
        ),
    ]
