# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PAN', models.CharField(max_length=10, verbose_name='PAN')),
                ('TAN', models.CharField(max_length=10, verbose_name='TAN')),
                ('STN', models.CharField(max_length=15, verbose_name='Service Tax Regn. No.')),
                ('DOB', models.DateField(verbose_name='Date of Birth')),
                ('Type', models.CharField(choices=[('individual', 'Individual'), ('llp', 'Limited Liability Partnership'), ('opc', 'One Person Company'), ('partnership', 'Partnership Firm'), ('pvt_ltd', 'Private Limited Company'), ('pub_ltd', 'Public Limited Company'), ('trust', 'Trust')], max_length=11, verbose_name='Client Type')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(max_length=1000, verbose_name='User Comments')),
                ('First_Name', models.CharField(max_length=20, verbose_name='First Name')),
                ('Middle_Name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Middle Name')),
                ('Last_Name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, verbose_name='Gender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
