# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='Type',
        ),
        migrations.AddField(
            model_name='individual',
            name='CExNo',
            field=models.CharField(max_length=15, null=True, verbose_name='Central Excise Regn. No.'),
        ),
    ]
