# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='CExNo',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Central Excise Regn. No.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='PAN',
            field=models.CharField(help_text='Mandatory', max_length=10, unique=True, verbose_name='PAN'),
        ),
        migrations.AlterField(
            model_name='client',
            name='STN',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Service Tax Regn. No.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='TAN',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='TAN'),
        ),
        migrations.AlterField(
            model_name='limited_company',
            name='Company_CIN',
            field=models.CharField(help_text='Mandatory', max_length=21, unique=True, verbose_name='Company CIN'),
        ),
        migrations.AlterField(
            model_name='limited_company',
            name='Company_Name',
            field=models.CharField(help_text='Mandatory', max_length=120, unique=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='llp',
            name='LLPIN',
            field=models.CharField(help_text='Mandatory', max_length=8, unique=True, verbose_name='LLP Identification Number'),
        ),
        migrations.AlterField(
            model_name='llp',
            name='LLP_Name',
            field=models.CharField(help_text='Mandatory', max_length=80, unique=True, verbose_name='LLP Name'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='Partnership_Name',
            field=models.CharField(help_text='Mandatory', max_length=80, unique=True, verbose_name='LLP Name'),
        ),
    ]
