# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20160710_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='address',
            name='PIN',
            field=models.CharField(help_text='Mandatory', max_length=6),
        ),
    ]
