# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20160706_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='DOB',
            field=models.DateField(help_text='Mandatory', verbose_name='Date of Birth / Registration'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='First_Name',
            field=models.CharField(help_text='Mandatory', max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='Gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], help_text='Mandatory', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='Last_Name',
            field=models.CharField(help_text='Mandatory', max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='PAN',
            field=models.CharField(help_text='Mandatory', max_length=10, verbose_name='PAN'),
        ),
    ]
