# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20160715_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='_my_subclass',
            field=models.CharField(max_length=200),
        ),
    ]
